-- 사용자 테이블
CREATE TABLE USERINFO(
	ID VARCHAR2(10) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	AUTH CHAR(1) NOT NULL,
	ENABLE CHAR(1) NOT NULL,
	JOINDATE DATE NOT NULL
);

ALTER TABLE USERINFO ADD CONSTRAINT EMAIL_UQ UNIQUE(EMAIL);
ALTER TABLE USERINFO ADD CONSTRAINT USERINFO_PK PRIMARY KEY(ID);

-- 답글 게시판
CREATE TABLE ANSWERBOARD(
	SEQ NUMBER,
	ID VARCHAR2(10) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(1000),
	REF NUMBER NOT NULL,
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	REGDATE DATE NOT NULL,
	DELFLAG CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE ANSWERBOARD_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE ANSWERBOARD ADD CONSTRAINT ANSWERBOARD_PK PRIMARY KEY(SEQ);

ALTER TABLE ANSWERBOARD ADD CONSTRAINT ANSWERBOARD_FK FOREIGN KEY (ID) REFERENCES USERINFO(ID);



-- 사용자 더미 데이터
INSERT INTO USERINFO u (ID,NAME,PASSWORD,EMAIL,AUTH,ENABLE,JOINDATE)
	VALUES('A001','코코볼','A001','A001@naver.com','U','Y',CURRENT_TIMESTAMP);
INSERT INTO USERINFO u (ID,NAME,PASSWORD,EMAIL,AUTH,ENABLE,JOINDATE)
	VALUES('A002','코코볼','A002','A002@naver.com','U','Y',CURRENT_TIMESTAMP);
INSERT INTO USERINFO u (ID,NAME,PASSWORD,EMAIL,AUTH,ENABLE,JOINDATE)
	VALUES('A003','코코볼','A003','A003@naver.com','A','Y',CURRENT_TIMESTAMP);

UPDATE USERINFO SET NAME='햇빛' WHERE ID='A002';
UPDATE USERINFO SET NAME='관리자' WHERE ID='A003';
SELECT * FROM USERINFO u ;

SELECT ID,NAME,AUTH,JOINDATE 
	FROM USERINFO u 
	WHERE ID='A001' AND PASSWORD='A001';
