-- 답변형 게시판

-- ROOT 글 입력
SELECT ANSWERBOARD_SEQ.NEXTVAL
 FROM DUAL;
 
SELECT NVL(MAX(SEQ),0)+1
 FROM ANSWERBOARD a ;
 
INSERT INTO ANSWERBOARD a (SEQ,ID,TITLE,CONTENT,"REF",STEP,"DEPTH",REGDATE,DELFLAG)
VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A001','ROOT글 첫번째','첫번째 ROOT 글의 내용 작성',(SELECT NVL(MAX(REF),0)+1 FROM ANSWERBOARD a),0,0,SYSDATE,'N');

INSERT INTO ANSWERBOARD a (SEQ,ID,TITLE,CONTENT,"REF",STEP,"DEPTH",REGDATE,DELFLAG)
VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A002','ROOT글 두번째','두번째 ROOT 글의 내용 작성',(SELECT NVL(MAX(REF),0)+1 FROM ANSWERBOARD a),0,0,SYSDATE,'N');

SELECT SEQ,ID, 
		CASE DELFLAG 
			WHEN 'Y' THEN '--삭제된 글입니다--' 
			ELSE LPAD(' ',DEPTH*10)||TITLE 
			END AS TITLE,
"REF",STEP,"DEPTH",REGDATE,DELFLAG,NAME
 FROM ANSWERBOARD a JOIN USERINFO u 
 USING(ID)
 ORDER BY REF DESC, STEP;
 
-- 상세글 조회
SELECT SEQ,ID,TITLE,CONTENT,REGDATE
 FROM ANSWERBOARD a 
 WHERE SEQ='11';


INSERT INTO ANSWERBOARD a (SEQ,ID,TITLE,CONTENT,"REF",STEP,"DEPTH",REGDATE,DELFLAG)
VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A001','ROOT글 삭제글','두번째 ROOT 글의 삭제내용 작성',(SELECT NVL(MAX(REF),0)+1 FROM ANSWERBOARD a),0,0,SYSDATE,'Y');


-- 글 수정
UPDATE ANSWERBOARD SET CONTENT='두번째 ROOT 글의 삭제내용 작성'
 WHERE SEQ='11';
 
SELECT CONTENT
FROM ANSWERBOARD a 
WHERE SEQ='11';

-- 글 삭제
UPDATE ANSWERBOARD
 SET DELFLAG ='Y'
 WHERE SEQ='10';

-- 답글(Transaction 처리)
-- 1) 입력되는 값보다 큰 STEP을 찾아서 모두 +1 해준다
UPDATE ANSWERBOARD SET STEP=STEP+1
	WHERE REF=(SELECT REF FROM ANSWERBOARD a WHERE SEQ='11')
	AND STEP>(SELECT STEP FROM ANSWERBOARD a WHERE SEQ='11');

SELECT * FROM ANSWERBOARD a ;




-- 2) 부모의 REF 사용, 부모의 STEP+1, 부모의 DEPTH+1
INSERT INTO ANSWERBOARD
(SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
VALUES(ANSWERBOARD_SEQ.NEXTVAL, 
'A001', '답글4', '답글4 내용', (SELECT REF FROM ANSWERBOARD a WHERE SEQ='11'),(SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ='11')+1,(SELECT "DEPTH" FROM ANSWERBOARD a2 WHERE SEQ='11')+1, SYSDATE,'N');


DELETE FROM ANSWERBOARD WHERE TITLE='답글2'; 
 