-- ANSWERBOARD PAGING SQL

SELECT SEQ , ID , TITLE ,
         CONTENT , "REF" , STEP ,
         "DEPTH" , REGDATE , DELFLAG 
   FROM(
      SELECT ROW_NUMBER() OVER(ORDER BY REF DESC , STEP) RN ,
            SEQ , ID , TITLE ,
            CONTENT , "REF" , STEP ,
            "DEPTH" , TO_CHAR(REGDATE, 'YYYY-MM-DD hh:mm:ss') REGDATE , DELFLAG 
         FROM ANSWERBOARD a 
   )
   WHERE RN BETWEEN 6 AND 10;
   
-- 전체글의 갯수
SELECT COUNT(*)
   FROM ANSWERBOARD a ;
   
  
INSERT INTO ANSWERBOARD
(SEQ, ID, TITLE,
CONTENT, "REF", STEP,
"DEPTH", REGDATE, DELFLAG)
VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A002', 'ROOT글 두번째'||ANSWERBOARD_SEQ.CURRVAL,
'두번째 ROOT 글의 내용 작성', (SELECT NVL(MAX(REF),0)+1 FROM ANSWERBOARD a), 0,
0, SYSDATE, 'N');