--답변형 게시판 + 파일 업로드 다운로드 게시판

CREATE TABLE ANSWERBOARD(
SEQ NUMBER,
ID VARCHAR2(20) NOT NULL,
TITLE VARCHAR2(200) NOT NULL,
CONTENT VARCHAR2(1000),
REF NUMBER NOT NULL,
STEP NUMBER NOT NULL,
DEPTH NUMBER NOT NULL,
REGDATE DATE NOT NULL,
DELFLAG CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE ANSWERBOARD_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE ANSWERBOARD ADD CONSTRAINT ANSWERBOARD_PK PRIMARY KEY (SEQ);


CREATE TABLE FILEBOARD(
	F_SEQ NUMBER PRIMARY KEY NOT NULL,
	B_SEQ NUMBER NOT NULL,
	WRITER VARCHAR2(100),
	ORIGIN_FNAME VARCHAR2(1000) NOT NULL,
	STORED_FNAME VARCHAR2(1000) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	F_REGDATE DATE NOT NULL,
	F_DELFLAG CHAR(1) NOT NULL
);

CREATE SEQUENCE FILEBOARD_SEQ START WITH 1 INCREMENT BY 1;

--게시글에 파일이 없어도 리스트 출력이 가능해야 함 - LEFT OUTER JOIN
SELECT SEQ, ID, TITLE, CONTENT, REGDATE, 
	   ORIGIN_FNAME, WRITER 
 FROM ANSWERBOARD a LEFT JOIN FILEBOARD f
 ON a.SEQ =f.B_SEQ;

--새로 작성된 글(파일 있음)
SELECT SEQ,ID,TITLE||'('|| CNT||')', TITLE, CONTENT,REGDATE
FROM (SELECT SEQ,ID,TITLE,(SELECT COUNT(*) FROM FILEBOARD f
						WHERE a.SEQ=f.B_SEQ) CNT, CONTENT, REGDATE
					,ROW_NUMBER() OVER(ORDER BY REF DESC, STEP ASC) RN
 FROM ANSWERBOARD a)
 WHERE RN<11;



--상세글
SELECT SEQ, ID, WRITER, TITLE, CONTENT, REGDATE, ORIGIN_FNAME 
 FROM ANSWERBOARD a LEFT JOIN FILEBOARD F
 ON a.SEQ=f.B_SEQ
 WHERE SEQ='80';